services:
  - type: web
    name: playstop-backend
    runtime: docker
    repo: https://github.com/SHEILAJPM/PlayStop-Backend
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: APP_BASE_URL
        value: https://playstop-backend-1.onrender.com
